require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

# Ignore DSLs
Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "**/*.rake"
    - "spec/**/*.rb"
